# Generated by Django 3.2.23 on 2024-01-05 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_stamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('modified_stamp', models.DateTimeField(auto_now=True)),
                ('archived_stamp', models.DateTimeField(null=True)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('text', models.CharField(max_length=4096)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'joke',
            },
        ),
        migrations.CreateModel(
            name='JokeSeen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_stamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('joke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Joke.joke')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'joke_seen',
            },
        ),
        migrations.CreateModel(
            name='JokeLikeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=None, null=True)),
                ('joke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Joke.joke')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'joke_like_status',
            },
        ),
        migrations.AddIndex(
            model_name='jokeseen',
            index=models.Index(fields=['joke', 'user'], name='joke_seen_joke_id_c808bf_idx'),
        ),
        migrations.AddIndex(
            model_name='jokelikestatus',
            index=models.Index(fields=['joke', 'user'], name='joke_like_s_joke_id_acf815_idx'),
        ),
    ]
