# Generated by Django 3.2.23 on 2024-01-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Joke', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jokelikestatus',
            index=models.Index(fields=['is_liked', 'user'], name='joke_like_s_is_like_15d509_idx'),
        ),
    ]
