# Generated by Django 3.2.23 on 2024-01-31 17:25

from django.db import migrations


def public_registration(apps, schema_editor):
    EmailNotification = apps.get_model('Emailer', 'EmailNotification')

    subject = 'Joker registration'
    email_template_path = 'core/Emailer/templates/public_registration_email.html'
    notification, created = EmailNotification.objects.get_or_create(
        slug='public_registration_email',
        defaults={
            'subject': subject,
            'email_template_path': email_template_path,
        }
    )

    if not created:
        notification.subject = subject
        notification.email_template_path = email_template_path
        notification.save()


class Migration(migrations.Migration):
    dependencies = [
        ('Emailer', '0002_create_forgot_password_emails'),
    ]

    operations = [
        migrations.RunPython(public_registration),
    ]
