# Generated by Django 3.2.23 on 2024-01-31 17:25

from django.db import migrations


def joke_send_via_email(apps, schema_editor):
    EmailNotification = apps.get_model('Emailer', 'EmailNotification')

    subject = 'Joke'
    email_template_path = 'core/Emailer/templates/joke_email.html'
    notification, created = EmailNotification.objects.get_or_create(
        slug='joke_email',
        defaults={
            'subject': subject,
            'email_template_path': email_template_path,
        }
    )

    if not created:
        notification.subject = subject
        notification.email_template_path = email_template_path
        notification.save()


class Migration(migrations.Migration):
    dependencies = [
        ('Emailer', '0003_create_public_registration_email'),
    ]

    operations = [
        migrations.RunPython(joke_send_via_email),
    ]
